import PDFDocument from 'pdfkit';
import fs from 'fs';
import dayjs from 'dayjs';

export interface PdfTableColumn {
  header: string;
  width: number;
  align?: 'left' | 'right' | 'center';
}

export interface PdfBrand {
  logoPath?: string;
  fontFamily?: string; // 'Helvetica' | 'Times-Roman' | 'Courier'
  scale?: number; // percentage, e.g. 90
}

export interface PdfBuildOptions extends PdfBrand {
  title: string;
  businessName: string;
  businessAddress?: string;
  businessPhone?: string;
  businessGstin?: string;
  docMeta: { label: string; value: string }[];
  columns: PdfTableColumn[];
  rows: (string | number)[][];
  totals?: { label: string; value: string }[];
  footer?: string;
}

const NAVY = '#0f2f4c';
const MUTED = '#5b7186';
const LINE = '#d7e2ea';

const BOLD_MAP: Record<string, string> = {
  Helvetica: 'Helvetica-Bold',
  'Times-Roman': 'Times-Bold',
  Courier: 'Courier-Bold',
};

export function resolveFonts(fontFamily?: string) {
  const regular = fontFamily && BOLD_MAP[fontFamily] ? fontFamily : 'Helvetica';
  return { regular, bold: BOLD_MAP[regular] };
}

/** Applies the configured page scale (e.g. 90%) so content shrinks to fit A4 reliably. */
function applyScale(doc: PDFKit.PDFDocument, scale?: number) {
  const pct = scale && scale > 0 && scale <= 150 ? scale : 100;
  if (pct !== 100) doc.scale(pct / 100, pct / 100, { origin: [0, 0] });
}

function drawLogo(doc: PDFKit.PDFDocument, logoPath: string | undefined, x: number, y: number, maxHeight: number) {
  if (!logoPath) return 0;
  try {
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, x, y, { fit: [maxHeight * 2.2, maxHeight] });
      return maxHeight * 2.2 + 12;
    }
  } catch {
    // Corrupt/unsupported image — skip the logo rather than fail the whole PDF.
  }
  return 0;
}

export function buildDocumentPdf(opts: PdfBuildOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    applyScale(doc, opts.scale);
    const { regular, bold } = resolveFonts(opts.fontFamily);

    const logoWidth = drawLogo(doc, opts.logoPath, 40, 36, 34);
    const nameX = 40 + logoWidth;

    doc.fillColor(NAVY).fontSize(18).font(bold).text(opts.businessName, nameX, 40, { width: 300 - logoWidth });
    doc.fontSize(9).font(regular).fillColor(MUTED);
    if (opts.businessAddress) doc.text(opts.businessAddress, nameX, doc.y, { width: 300 - logoWidth });
    const contactLine = [opts.businessPhone, opts.businessGstin ? `GSTIN: ${opts.businessGstin}` : null].filter(Boolean).join('  |  ');
    if (contactLine) doc.text(contactLine, nameX, doc.y, { width: 300 - logoWidth });

    doc.fontSize(14).font(bold).fillColor(NAVY).text(opts.title, 40, 40, { align: 'right' });
    let metaY = 60;
    doc.fontSize(9).font(regular).fillColor(MUTED);
    for (const m of opts.docMeta) {
      doc.text(`${m.label}: ${m.value}`, 350, metaY, { align: 'right', width: 205 });
      metaY += 13;
    }

    doc.moveTo(40, 115).lineTo(555, 115).strokeColor(LINE).stroke();

    let y = 130;
    const tableX = 40;
    let x = tableX;
    doc.font(bold).fontSize(9).fillColor('#ffffff');
    doc.rect(tableX, y, 515, 20).fill(NAVY);
    doc.fillColor('#ffffff');
    for (const col of opts.columns) {
      doc.text(col.header, x + 4, y + 6, { width: col.width - 8, align: col.align ?? 'left' });
      x += col.width;
    }
    y += 20;

    doc.font(regular).fontSize(9);
    for (const [i, row] of opts.rows.entries()) {
      if (y > 760) {
        doc.addPage();
        y = 40;
      }
      if (i % 2 === 0) {
        doc.rect(tableX, y, 515, 18).fill('#f4f8fb');
      }
      doc.fillColor('#1e2b36');
      x = tableX;
      for (const [ci, col] of opts.columns.entries()) {
        doc.text(String(row[ci] ?? ''), x + 4, y + 4, { width: col.width - 8, align: col.align ?? 'left' });
        x += col.width;
      }
      y += 18;
    }

    doc.moveTo(40, y + 4).lineTo(555, y + 4).strokeColor(LINE).stroke();
    y += 12;

    if (opts.totals) {
      for (const t of opts.totals) {
        doc.font(bold).fontSize(10).fillColor(NAVY).text(t.label, 350, y, { width: 120, align: 'right' });
        doc.font(regular).text(t.value, 470, y, { width: 85, align: 'right' });
        y += 16;
      }
    }

    doc.fontSize(8).fillColor(MUTED).text(
      opts.footer || `Generated by BusinessFlow ERP on ${dayjs().format('DD-MMM-YYYY, HH:mm')}`,
      40,
      800,
      { align: 'center', width: 515 }
    );

    doc.end();
  });
}

// ============================================================
// TAX INVOICE (Sales Invoice) — matches the classic boxed
// Bill To / Ship To / GST%+Discount% tax-invoice layout.
// ============================================================

export interface TaxInvoiceItem {
  name: string;
  qty: string;
  unit: string;
  rate: string;
  gstPercent: string;
  discountPercent: string;
  amount: string;
}

export interface TaxInvoiceOptions extends PdfBrand {
  businessName: string;
  businessAddress?: string;
  businessPhone?: string;
  businessGstin?: string;
  businessEmail?: string;
  invoiceNo: string;
  date: string;
  customerId: string;
  billTo: { name: string; address?: string; gstin?: string; phone?: string; email?: string };
  shipTo: { name: string; address?: string; gstin?: string; phone?: string; email?: string };
  items: TaxInvoiceItem[];
  totalTaxableValue: string;
  gstAmount: string;
  discount: string;
  totalValue: string;
  termsConditions?: string;
}

const COLS = [
  { key: 'sr', header: 'Sr. No.', width: 35, align: 'center' as const },
  { key: 'name', header: 'Item Name', width: 155, align: 'left' as const },
  { key: 'qty', header: 'Qty', width: 40, align: 'right' as const },
  { key: 'unit', header: 'Unit', width: 45, align: 'center' as const },
  { key: 'rate', header: 'Rate/Price', width: 65, align: 'right' as const },
  { key: 'gst', header: 'GST%', width: 45, align: 'right' as const },
  { key: 'disc', header: 'Discount%', width: 55, align: 'right' as const },
  { key: 'amount', header: 'Amount', width: 75, align: 'right' as const },
];

const TITLE_GRAY = '#d9d9d9';
const ACCENT_BLUE = '#4f81bd';
const ACCENT_BLUE_DARK = '#1f4e79';
const TOTALS_GREEN = '#d8e4bc';
const GRAY = '#444444';

function partyBlock(doc: PDFKit.PDFDocument, x: number, y: number, width: number, title: string, party: TaxInvoiceOptions['billTo'], regular: string, bold: string) {
  doc.rect(x, y, width, 18).fillAndStroke(ACCENT_BLUE, '#000000');
  doc.font(bold).fontSize(10).fillColor('#ffffff').text(title, x, y + 4, { width, align: 'center' });
  let ly = y + 18 + 6;
  doc.font(bold).fontSize(9).fillColor(ACCENT_BLUE_DARK).text(party.name, x + 6, ly, { width: width - 12 });
  ly = doc.y + 2;
  doc.font(regular).fontSize(8.5).fillColor(GRAY);
  if (party.address) {
    doc.text(party.address, x + 6, ly, { width: width - 12 });
    ly = doc.y + 2;
  }
  if (party.gstin) {
    doc.text(`GSTIN: ${party.gstin}`, x + 6, ly, { width: width - 12 });
    ly = doc.y + 2;
  }
  const contact = [party.phone, party.email].filter(Boolean).join('  |  ');
  if (contact) {
    doc.text(contact, x + 6, ly, { width: width - 12 });
    ly = doc.y + 2;
  }
  return Math.max(ly + 6, y + 90);
}

export function buildTaxInvoicePdf(opts: TaxInvoiceOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    applyScale(doc, opts.scale);
    const { regular, bold } = resolveFonts(opts.fontFamily);

    doc.rect(40, 40, 515, 760).strokeColor('#000000').lineWidth(1).stroke();

    doc.rect(40, 40, 515, 28).fillAndStroke(TITLE_GRAY, '#000000');
    doc.font(bold).fontSize(18).fillColor('#000000').text('Tax Invoice', 40, 48, { align: 'center', width: 515 });

    const logoWidth = drawLogo(doc, opts.logoPath, 48, 84, 30);
    doc.font(bold).fontSize(11).fillColor(ACCENT_BLUE_DARK).text(opts.businessName, 48 + logoWidth, 84, { width: 300 - logoWidth });
    doc.font(regular).fontSize(8.5).fillColor(GRAY);
    if (opts.businessAddress) doc.text(opts.businessAddress, 48 + logoWidth, doc.y, { width: 300 - logoWidth });
    const bizContact = [opts.businessPhone, opts.businessEmail].filter(Boolean).join('  |  ');
    if (bizContact) doc.text(bizContact, 48 + logoWidth, doc.y, { width: 300 - logoWidth });
    if (opts.businessGstin) doc.text(`GST Number: ${opts.businessGstin}`, 48 + logoWidth, doc.y, { width: 300 - logoWidth });

    doc.font(regular).fontSize(9).fillColor('#000000');
    doc.text(`Date          :-  ${opts.date}`, 360, 88, { width: 190, align: 'left' });
    doc.text(`Invoice No.   :-  ${opts.invoiceNo}`, 360, 102, { width: 190, align: 'left' });
    doc.text(`Customer ID   :-  ${opts.customerId}`, 360, 116, { width: 190, align: 'left' });

    const partyY = 150;
    doc.moveTo(40, partyY - 6).lineTo(555, partyY - 6).strokeColor(LINE).stroke();
    const billBottom = partyBlock(doc, 40, partyY, 257, 'Bill To', opts.billTo, regular, bold);
    const shipBottom = partyBlock(doc, 298, partyY, 257, 'Ship To', opts.shipTo, regular, bold);
    let y = Math.max(billBottom, shipBottom) + 8;

    doc.moveTo(40, y).lineTo(555, y).strokeColor('#000000').stroke();
    y += 2;

    doc.font(bold).fontSize(8);
    let x = 40;
    for (const col of COLS) {
      doc.rect(x, y, col.width, 20).fillAndStroke(ACCENT_BLUE, '#000000');
      doc.fillColor('#ffffff').text(col.header, x + 2, y + 6, { width: col.width - 4, align: col.align });
      x += col.width;
    }
    y += 20;

    doc.font(regular).fontSize(8.5).fillColor('#000000');
    opts.items.forEach((item, i) => {
      if (y > 700) {
        doc.addPage();
        y = 40;
      }
      const cells = [String(i + 1), item.name, item.qty, item.unit, item.rate, item.gstPercent, item.discountPercent, item.amount];
      x = 40;
      const rowHeight = 18;
      for (const [ci, col] of COLS.entries()) {
        doc.rect(x, y, col.width, rowHeight).strokeColor(LINE).stroke();
        doc.text(cells[ci], x + 2, y + 5, { width: col.width - 4, height: doc.currentLineHeight(), align: col.align, ellipsis: true });
        x += col.width;
      }
      y += rowHeight;
    });

    // Pad empty rows so the table has a consistent minimum height, like the paper template.
    const minRows = 14;
    for (let i = opts.items.length; i < minRows; i++) {
      if (y > 700) {
        doc.addPage();
        y = 40;
      }
      x = 40;
      for (const col of COLS) {
        doc.rect(x, y, col.width, 16).strokeColor(LINE).stroke();
        x += col.width;
      }
      y += 16;
    }

    y += 6;
    const boxTop = y;
    const termsWidth = 330;
    const totalsWidth = 185;

    doc.rect(40, y, termsWidth, 16).fillAndStroke(ACCENT_BLUE, '#000000');
    doc.font(bold).fontSize(9).fillColor('#ffffff').text('Terms & Conditions', 40, y + 4, { width: termsWidth, align: 'center' });
    doc.font(regular).fontSize(8).fillColor(MUTED).text(
      opts.termsConditions || '1. Total payment due within 30 days.\n2. Please include the invoice number on payment.',
      40,
      y + 16 + 4,
      { width: termsWidth }
    );

    const totalsX = 40 + termsWidth + 5;
    const totalsRows: [string, string][] = [
      ['Total Taxable Value', opts.totalTaxableValue],
      ['GST Amount', opts.gstAmount],
      ['Discount', opts.discount],
      ['Total Value', opts.totalValue],
    ];
    let ty = boxTop;
    for (const [label, value] of totalsRows) {
      doc.rect(totalsX, ty, totalsWidth, 18).fillAndStroke(TOTALS_GREEN, LINE);
      doc.font(bold).fontSize(8.5).fillColor('#000000').text(label, totalsX + 4, ty + 5, { width: totalsWidth * 0.6 });
      doc.font(regular).text(value, totalsX + totalsWidth * 0.6, ty + 5, { width: totalsWidth * 0.4 - 6, align: 'right' });
      ty += 18;
    }

    doc.fontSize(8).fillColor(MUTED).text(
      `Generated by BusinessFlow ERP on ${dayjs().format('DD-MMM-YYYY, HH:mm')}`,
      40,
      785,
      { align: 'center', width: 515 }
    );

    doc.end();
  });
}
