import PDFDocument from 'pdfkit';
import dayjs from 'dayjs';

export interface PdfTableColumn {
  header: string;
  width: number;
  align?: 'left' | 'right' | 'center';
}

export interface PdfBuildOptions {
  title: string;
  businessName: string;
  businessAddress?: string;
  businessPhone?: string;
  businessGstin?: string;
  docMeta: { label: string; value: string }[];
  columns: PdfTableColumn[];
  rows: (string | number)[][];
  totals?: { label: string; value: string }[];
  footer?: string;
}

const NAVY = '#0f2f4c';
const MUTED = '#5b7186';
const LINE = '#d7e2ea';

export function buildDocumentPdf(opts: PdfBuildOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fillColor(NAVY).fontSize(18).font('Helvetica-Bold').text(opts.businessName, 40, 40);
    doc.fontSize(9).font('Helvetica').fillColor(MUTED);
    if (opts.businessAddress) doc.text(opts.businessAddress);
    const contactLine = [opts.businessPhone, opts.businessGstin ? `GSTIN: ${opts.businessGstin}` : null].filter(Boolean).join('  |  ');
    if (contactLine) doc.text(contactLine);

    doc.fontSize(14).font('Helvetica-Bold').fillColor(NAVY).text(opts.title, 40, 40, { align: 'right' });
    let metaY = 60;
    doc.fontSize(9).font('Helvetica').fillColor(MUTED);
    for (const m of opts.docMeta) {
      doc.text(`${m.label}: ${m.value}`, 350, metaY, { align: 'right', width: 205 });
      metaY += 13;
    }

    doc.moveTo(40, 115).lineTo(555, 115).strokeColor(LINE).stroke();

    let y = 130;
    const tableX = 40;
    let x = tableX;
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff');
    doc.rect(tableX, y, 515, 20).fill(NAVY);
    doc.fillColor('#ffffff');
    for (const col of opts.columns) {
      doc.text(col.header, x + 4, y + 6, { width: col.width - 8, align: col.align ?? 'left' });
      x += col.width;
    }
    y += 20;

    doc.font('Helvetica').fontSize(9);
    for (const [i, row] of opts.rows.entries()) {
      if (y > 760) {
        doc.addPage();
        y = 40;
      }
      if (i % 2 === 0) {
        doc.rect(tableX, y, 515, 18).fill('#f4f8fb');
      }
      doc.fillColor('#1e2b36');
      x = tableX;
      for (const [ci, col] of opts.columns.entries()) {
        doc.text(String(row[ci] ?? ''), x + 4, y + 4, { width: col.width - 8, align: col.align ?? 'left' });
        x += col.width;
      }
      y += 18;
    }

    doc.moveTo(40, y + 4).lineTo(555, y + 4).strokeColor(LINE).stroke();
    y += 12;

    if (opts.totals) {
      for (const t of opts.totals) {
        doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY).text(t.label, 350, y, { width: 120, align: 'right' });
        doc.font('Helvetica').text(t.value, 470, y, { width: 85, align: 'right' });
        y += 16;
      }
    }

    doc.fontSize(8).fillColor(MUTED).text(
      opts.footer || `Generated by BusinessFlow ERP on ${dayjs().format('DD MMM YYYY, HH:mm')}`,
      40,
      800,
      { align: 'center', width: 515 }
    );

    doc.end();
  });
}
