-- AlterTable
ALTER TABLE `Purchase` ADD COLUMN `vendorBillDate` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `PurchaseOrder` ADD COLUMN `discount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `grandTotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `subtotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `PurchaseOrderItem` ADD COLUMN `discount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxRate` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `total` DECIMAL(14, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `SalesOrder` ADD COLUMN `discount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `grandTotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `subtotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `SalesOrderItem` ADD COLUMN `discount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxRate` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `total` DECIMAL(14, 2) NOT NULL DEFAULT 0;
